[feat-48818]: hook for making adjustments of tx deploy value
web3-nomad/accelerator-defi-EIP-ui pull request #93
Opened 2024-10-14 13:41 UTC by maryjanyes

2024-10-15 12:04 UTC, dchernokur requested changes

2024-10-15 12:04 UTC, dchernokur commented on src/hooks/eip4626/mutations/useDeployVault.ts
> +  }, [mut.isError]);
why have separate field for the error, can we use the error from mutation directly?

2024-10-15 12:04 UTC, dchernokur commented on src/hooks/useDeployValueSafeTx.ts
> +    useState<string>("0");
no need for explicit typings, if we have default values

2024-10-15 12:04 UTC, dchernokur commented on src/hooks/useDeployValueSafeTx.ts
> +      rateResponse.json().then((rateData) => {
why not async/await?

2024-10-16 11:42 UTC, maryjanyes commented on src/hooks/eip4626/mutations/useDeployVault.ts
> +    0.9,
> what is this 0.9 value and where it comes from? do we need a const with telling name for it maybe?

Yeah, good proposal. It's about initial value in fiat.

2024-10-16 12:04 UTC, dchernokur approved these changes

2024-10-17 08:24 UTC, merged